import './globals.css'
import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'

import { AuthProvider } from '@/context/AuthProvider'

const leagueSpartan = League_Spartan({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	themeColor: [
		{ media: '(prefers-color-scheme: light)', color: '#9277FF' },
		{ media: '(prefers-color-scheme: dark)', color: '#9277FF' },
	],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${leagueSpartan.className} bg-lightGray dark:bg-black transition-colors duration-250 `}>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	)
}
